# application name

# server port number [recommended 1337]

# h2 database connection url

# h2 database driver class

# database username

# database password

# jpa dialect for h2 database

# create and drop tables automatically

# show sql queries in console

# always initialize database scripts

# enable h2 database console

# h2 console access path
